Cake_Buffet/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('',include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import (
    MenuListView,
    menuDetail,
    add_to_cart,
    get_cart_items,
    order_item,
    user_order_details,
    order_details,
    CartDeleteView,
    profile,
    CustomView,
    custom_menu,
    custom_cart,
    custom_user_dtl,
    custom_user_order_details,
    cake_reviews,
)
app_name = "main"

urlpatterns = [
    path('', MenuListView.as_view(), name='home'),
    path('dishes/<slug>', views.menuDetail, name='dishes'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.get_cart_items, name='cart'),
    path('remove-from-cart/<int:pk>/', views.CartDeleteView.as_view(), name='remove-from-cart'),
    path('ordered/', views.order_item, name='ordered'),
    path('user-order-details',views.user_order_details,name='user_order_details'),
    path('order_details/', views.order_details, name='order_details'),
    path('profile/',views.profile,name='profile'),
    path('custom-order', CustomView.as_view(), name='custom'),
    path('custom-order-menu/<slug>', views.custom_menu, name='custom_menu'),
    path('custom-order-details/<slug>',views.custom_cart,name='custom_cart'),
    path('custom-user-dtl/',views.custom_user_dtl,name='custom_user_dtl'),
    path('custom-user-order-details/',views.custom_user_order_details,name='custom_uod'),
    path('cake-review/',views.cake_reviews,name="cake_reviews"),

]

main/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db.models import signals
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.shortcuts import reverse
from users.models import Customer
# Create your models here.

class Item(models.Model):
    LABELS = (
        ('Premium', 'Premium'),
        ('Eggless', 'Eggless'),
        ('Normal', 'Normal'),
    )   

    LABEL_COLOUR = (
        ('danger', 'danger'),
        ('success', 'success'),
        ('primary', 'primary'),
        ('info', 'info'),
        ('warning', 'warning'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=250,blank=True)
    price = models.FloatField()
    pieces = models.IntegerField(default=1)
    instructions = models.CharField(max_length=250,default="Available")
    image = models.ImageField(upload_to='images/')
    labels = models.CharField(max_length=25, choices=LABELS, blank=True)
    label_colour = models.CharField(max_length=15, choices=LABEL_COLOUR, blank=True)
    slug = models.SlugField(default="cakes")
    created_by = models.ForeignKey(Customer, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Cake'
        verbose_name_plural = 'Cakes'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:dishes", kwargs={'slug': self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("main:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_item_delete_url(self):
        return reverse("main:item-delete", kwargs={
            'slug': self.slug
        })

    def get_update_item_url(self):
        return reverse("main:item-update", kwargs={
            'slug': self.slug
        })

class CartItems(models.Model):
    ORDER_STATUS = (
        ('Ordered', 'Ordered'),
        ('Delivered', 'Delivered'),
        ('Cancelled','Cancelled')
    )
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    delivery_addrs = models.CharField(max_length=400,blank=True,verbose_name='Current Delivery Address')
    inst = models.CharField(max_length=400,blank=True,verbose_name='Instructions')
    ordered_date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='Ordered')
    delivery_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return self.item.title
    
    def get_remove_from_cart_url(self):
        return reverse("main:remove-from-cart", kwargs={
            'pk' : self.pk
        })

    def update_status_url(self):
        return reverse("main:update_status", kwargs={
            'pk' : self.pk
        })

class CustomCakes(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    custom_title = models.CharField(max_length=150,verbose_name='Cake Name')
    custom_price = models.IntegerField(default=0,verbose_name='Price')
    custom_description = models.CharField(max_length=250,blank=True,verbose_name='Description')
    custom_image = models.ImageField(upload_to='custom_images/')
    custom_slug = models.SlugField(default="custom-cakes",verbose_name='Slug')

    class Meta:
        verbose_name = 'Custom Cake'
        verbose_name_plural = 'Custom Cakes'

    def __str__(self):
        return self.custom_title

    def get_custom_url(self):
        return reverse("main:custom_menu", kwargs={'cslug': self.custom_slug})

class Custom_Orders(models.Model):
    ORDER_STATUS = (
        ('Ordered', 'Ordered'),
        ('Delivered', 'Delivered'),
        ('Cancelled','Cancelled'),
        ('Waiting for confirmation','Waiting for confirmation'),
    )
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    custom_item = models.ForeignKey(CustomCakes, on_delete=models.CASCADE)
    custom_ordered = models.BooleanField(default=False,verbose_name='Ordered')
    quantity_in_kg = models.IntegerField(default=2)
    delivery_address = models.CharField(max_length=400,blank=True,verbose_name='Current Delivery Address')
    custom_total = models.IntegerField(default=0,verbose_name='Total Price')
    custom_instructions = models.CharField(max_length=400,blank=True,verbose_name='Instructions')
    custom_ordered_date = models.DateField(default=timezone.now,verbose_name='Ordered on')
    custom_status = models.CharField(max_length=40, choices=ORDER_STATUS, default='Waiting for confirmation',verbose_name='Order Status')
    custom_delivery_date = models.DateTimeField(default=timezone.now,verbose_name='Delivery Date')

    class Meta:
        verbose_name = 'Custom Order'
        verbose_name_plural = 'Custom Orders'

    def __str__(self):
        return self.custom_item.custom_title

    def save(self,*args,**kwargs):
        self.custom_total = self.custom_item.custom_price * self.quantity_in_kg
        super(Custom_Orders,self).save(*args,**kwargs)

class Reviews(models.Model):
    user = models.ForeignKey(Customer, on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    rslug = models.SlugField()
    review = models.TextField()
    posted_on = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.review

@receiver(pre_save, sender= CartItems,dispatch_uid='del_send')
def del_send(sender, instance,**kwargs):
    if instance.status == 'Delivered':
        user = instance.user
        sub = 'YOUR ORDER DELIVERED'
        msg = 'Hi %s Your order has been delivered' %(instance.user.first_name)
        frm_email = settings.EMAIL_HOST_USER
        to = [user.email]
        send_mail(sub, msg,frm_email,to)


@receiver(pre_save, sender= Custom_Orders,dispatch_uid='del_send')
def del_send(sender, instance,**kwargs):
    if instance.custom_status == 'Delivered':
        user = instance.user
        sub = 'YOUR CUSTOM ORDER DELIVERED'
        msg = 'Hi %s Your custom order has been delivered. Order Again !!!' %(instance.user.first_name)
        frm_email = settings.EMAIL_HOST_USER
        to = [user.email]
        send_mail(sub, msg,frm_email,to)

main/forms.py
from django import forms

class OrderDetailsForm(forms.Form):
    alt_name = forms.CharField(max_length=50)
    alt_phone = forms.CharField(max_length=10)
    address = forms.CharField(max_length=400)
    Order_instructions = forms.CharField(max_length=200)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Item,CartItems,CustomCakes,Custom_Orders,Reviews
from users.models import Customer
from django.contrib import messages
from django.views.generic.edit import DeleteView
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F
from django.conf import settings
from django.core.mail import send_mail


class MenuListView(ListView):
    model = Item
    template_name = 'home.html'
    context_object_name = 'menu_items'

def menuDetail(request, slug):
    item = Item.objects.filter(slug=slug).first() 
    reviews = Reviews.objects.filter(rslug=slug).order_by('-id')
    context = {
        'item' : item,
        'reviews':reviews,
    }
    return render(request, 'dishes.html', context)

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    cart_item = CartItems.objects.create(
        item=item,
        user=request.user,
        ordered=False,
    )
    messages.info(request, "Added to Cart!!!")
    return redirect("main:cart")

@login_required
def get_cart_items(request):
    cart_items = CartItems.objects.filter(user=request.user,ordered=False)
    bill = cart_items.aggregate(Sum('item__price'))
    number = cart_items.aggregate(Sum('quantity'))
    pieces = cart_items.aggregate(Sum('item__pieces'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    total_pieces = pieces.get("item__pieces__sum")
    context = {
        'cart_items':cart_items,
        'total': total,
        'count': count,
        'total_pieces': total_pieces
    }
    return render(request, 'cart.html', context)

class CartDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CartItems
    success_url = '/cart'

    def test_func(self):
        cart = self.get_object()
        if self.request.user == cart.user:
            return True
        return False

@login_required
def profile(request):
    user = Customer.objects.all()
    return render(request,"profile.html")

@login_required
def order_item(request):
    return render(request,"user_order_details.html")

@login_required
def user_order_details(request):
    cart_items = CartItems.objects.filter(user=request.user,ordered=False)
    ordered_date=timezone.now()



    delivery_addrs = request.POST.get('addr')
    inst = request.POST.get('ins')

    cart_items.update(delivery_addrs=delivery_addrs,inst=inst)
    cart_items.update(ordered=True,ordered_date=ordered_date)
    user= request.user
    subject = ' CAKEBUFFET ORDER SUCCESSFULL'
    sub = 'NEW ORDER ARRIVED'
    message = f'Hi!!!{user.username},Your cakes have been successfully ordered and Our deliver partner will reach the location within 30-40 minutes.Order Again!!!'
    msg = f'Our customer {user.username} have order a new item. Assign a deliver partner soon!!!'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [user.email]
    to = ['vigneshrauvk13@gmail.com']
    send_mail( subject, message, email_from, recipient_list )
    send_mail(sub, msg, email_from, to)
    messages.info(request, "Successfully Ordered!!!")
    return render(request,"order_successful.html")

@login_required
def order_details(request):
    items = CartItems.objects.filter(user=request.user, ordered=True,status="Ordered").order_by('-ordered_date')
    cart_items = CartItems.objects.filter(user=request.user, ordered=True,status="Delivered").order_by('-ordered_date')
    custom_cart_items = Custom_Orders.objects.filter(user=request.user,custom_ordered=True,custom_status="Waiting for confirmation").order_by('-custom_ordered_date')
    bill = items.aggregate(Sum('item__price'))
    number = items.aggregate(Sum('quantity'))
    pieces = items.aggregate(Sum('item__pieces'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    total_pieces = pieces.get("item__pieces__sum")
    context = {
        'items':items,
        'cart_items':cart_items,
        'custom_cart_items':custom_cart_items,
        'total': total,
        'count': count,
        'total_pieces': total_pieces,
    }
    return render(request, 'order_details.html', context)

class CustomView(ListView):
    model = CustomCakes
    template_name = 'custom_order.html'
    context_object_name = 'custom_items'

def custom_menu(request, slug):
    custom_item = CustomCakes.objects.filter(custom_slug=slug).first() 
    context = {
        'custom_item' : custom_item,
    }
    return render(request, 'cinfos.html', context)

@login_required
def custom_cart(request, slug):
    custom_item = get_object_or_404(CustomCakes, custom_slug=slug)
    custom_cart= Custom_Orders.objects.create(
        custom_item=custom_item,
        user=request.user,
        custom_ordered=False,
    )

    return redirect('main:custom_user_dtl')

@login_required
def custom_user_dtl(request):
    return render(request, 'custom_user_order_details.html')

@login_required
def custom_user_order_details(request):
    custom_cart_items = Custom_Orders.objects.filter(user=request.user,custom_ordered=False)
    custom_ordered_date=timezone.now()


    quantity_in_kg = request.POST.get('ckg')
    delivery_address = request.POST.get('caddr')
    custom_instructions = request.POST.get('cins')

    
    custom_cart_items.update(delivery_address=delivery_address,custom_instructions=custom_instructions,quantity_in_kg=quantity_in_kg)
    custom_cart_items.update(custom_ordered=True,custom_ordered_date=custom_ordered_date)
    user= request.user
    custom_subject = ' CAKEBUFFET CUSTOM ORDER SUCCESSFULL'
    custom_sub = 'NEW CUSTOM ORDER ARRIVED'
    custom_message = f'Hi!!!{user.username},Your customizing cake have been successfully ordered and Our deliver partner will reach the location within 3-4hours after the confirmation phone call by our admin.Order Again!!!'
    custom_msg = f'Our customer {user.username} have order a new customizing cake. Call the customer for the confirmation'
    custom_email_from = settings.EMAIL_HOST_USER
    custom_recipient_list = [user.email]
    custom_to = ['vigneshrauvk13@gmail.com']
    send_mail( custom_subject, custom_message, custom_email_from, custom_recipient_list )
    send_mail(custom_sub, custom_msg, custom_email_from, custom_to)
    messages.info(request, "Successfully Ordered!!!")
    return render(request,'order_successful.html')

@login_required
def cake_reviews(request):
    if request.method == "POST":
        user = request.user
        rslug = request.POST.get("rslug")
        item = Item.objects.get(slug=rslug)
        review = request.POST.get("review")

        reviews = Reviews(user=user, item=item, review=review, rslug=rslug)
        reviews.save()
        messages.success(request, "Thank You for the review !!")
    return redirect(f"/dishes/{item.slug}")

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Josefin+Sans:ital@1&family=Open+Sans:wght@500&family=Sacramento&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Cake Buffet</title>
    <style>
        body{
                font-family: 'Montserrat',sans-serif;
            }
        #ni{
              border: 1px solid white;
              background-color: white;
              border-radius: 5px;
              color: #691d94;
        }
        
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg" style="background-color:#691d94;">
    <a class="navbar-brand" href="{% url 'main:home' %}" style="padding:0px;">
      <img src="{% static 'cblogo.png' %}" style="height:60px;width: 150px;">
    </a>
    <button style="background-color: white;"class="navbar-toggler"type="button"data-toggle="collapse"data-target="#navbarNav"aria-controls="navbarNav"aria-expanded="false"aria-label="Toggle navigation">
        <i class="fa fa-bars" style="color: #691d94;font-size:29px;"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav ml-auto">
                <li><a href="{% url 'main:home' %}" id="ni"class="mr-3 nav-link ">Home</a></li>
            {% if user.is_authenticated %}
                  <li><a href="{% url 'main:profile' %}" id="ni"class="mr-3 nav-link ">Profile</a></li>
                  <li><a href="{% url 'main:cart' %}" id="ni"class="mr-3 nav-link ">My Cart</a></li>
                  <li><a href="{% url 'main:order_details' %}" id="ni"class="mr-3 nav-link ">My Orders</a></li>
                  <li>
                      <form class="logout-link" action="{% url 'logout' %}" method="post">
                          {% csrf_token %}
                          <button type="submit" style="outline-style: none;"id="ni"class="mr-3 nav-link ">Logout</button>
                      </form>
                  </li>
            {% else %}
                <li><a href="{% url 'login' %}" id="ni"class="mr-3 nav-link ">Login</a></li>
                <li><a href="{% url 'signup' %}" id="ni"class="mr-3 nav-link ">SignUp</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
  </nav>
    <main role="main">
        {% if messages %}
          {% for message in messages %}
            <div id="msg" class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
    </main>
    {% block content %}{% endblock %}
    <footer class="bg-light text-center text-white">
        <div class="container p-4 pb-0">
          <section class="mb-4">
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #3b5998;border-radius:28px;border-style: none;"
              href="#!"
              role="button"
              ><i class="fa fa-facebook-f"></i
            ></a>
      
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #55acee;border-radius:27px;border-style: none;"
              href="#!"
              role="button"
              ><i class="fa fa-twitter"></i
            ></a>
      
      
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #ac2bac;border-radius:28px;border-style: none;"
              href="https://www.instagram.com/cake_buffet_pondicherry/"
              role="button"
              ><i class="fa fa-instagram"></i
            ></a>
          </section>
        </div>   
          <strong class="text-muted">© copyrights all reserved by cakebuffet.com</strong>          
      </footer>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script>
          $('.carousel').carousel();
      </script>
      <script>
        var messagee = document.getElementById("msg");
        setTimeout(function(){
          messagee.style.display = "none";
        },2000);
      </script>
</body>
</html>

main/templates/cart.html
{% extends "base.html" %}
{% block content %}
<div class="cart">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 mt-5">
                <h3 class="text-center">My Cart</h3>
                {% if cart_items %}
                <div class="table-responsive">
                    <table class="table table-light">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for cart in cart_items %}
                        <tr>
                            <td>{{ cart.item.title }} <span class="badge badge-{{ cart.item.label_colour }}">{{ cart.item.labels }}</span></td>
                            <td>{{ cart.item.price }}</td>
                            <td><a style="background-color: #47278c;border-style: none;"class="btn btn-danger" href="{% url 'main:remove-from-cart' cart.id %}">Delete</a></td>
                        </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h4 class="text-center">Your cart is empty!</h4>
                {% endif %}
            </div>
            <div class="col-sm-3 mt-5 mb-3">
                <div class="content-section">
                    <h3 class="text-center">Order Summary</h3>
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light text-center text-dark">Selected items <span style="font-weight: bold;">{{ count }}</span></li>
                        <li class="list-group-item list-group-item-light text-center text-dark">Quantity <span style="font-weight: bold;">{{ total_pieces }}</span></li>
                        <li class="list-group-item list-group-item-light text-center text-dark">Total <span style="font-weight: bold;">Rs.{{ total }}</span></li>
                        <li class="list-group-item list-group-item-light text-center text-dark"><a style="background-color: #47278c;border-style: none;"class="btn btn-primary" href="{% url 'main:ordered' %}">Order</a></li>
                        <li class="list-group-item list-group-item-light text-center"><a style="background-color: #47278c;border-style: none;"class="btn btn-success" href="{% url 'main:home' %}">Add items</a></li>
                      </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/cinfos.html
{% extends "base.html" %}
{% block content %}
<div class="dishes">
  <main class="mt-3 pt-4 main">
    <div class="container dark-grey-text">
      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">
          <img src="{{ custom_item.custom_image.url }}" class="img-fluid mt-4" alt="">
        </div>
        <div class="col-md-6 mb-4 information">
          <div class="p-4 content">
            <div class="mt-0">
                <h2>{{ custom_item.custom_title }}</h2>
            </div>
            <div class="lead">
              {% if custom_item.custom_description %}
              <h5>{{ custom_item.custom_description }}</h5>
              {% endif %}
              <h3>Rs.{{ custom_item.custom_price }}</h3>
            </div>
            <a href="{% url 'main:custom_cart' custom_item.custom_slug %}" style="background-color:#47278c;border-style: none;"class="btn btn-success btn-md my-0 p">Order</a>
          </div>
        </div>
      </div>
      <hr>
    </div>
  </main>
</div>
{% endblock content %}

main/templates/custom_user_order_details.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <p class="h3 text-center mt-3">Order Details</p>
  <form method="POST" action="{% url 'main:custom_uod'%}">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleFormControlSelect1">Kg</label>
      <select class="form-control" name="ckg">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Alternate Address<small class="text-muted">*</small></label>
      <textarea class="form-control" name="caddr" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Instructions<small class="text-muted">(optional)</small></label>
        <textarea class="form-control" name="cins" rows="3"></textarea>
    </div>
    
    <button type="submit" style="background-color: #691d94;border-style: none;"class="btn btn-primary" >Place Order</button>
  </form>
</div>
{% endblock %}

main/templates/dishes.html
{% extends "base.html" %}
{% block content %}
<div class="dishes">
    <!--Main layout-->
  <main class="mt-3 pt-4 main">
    <div class="container dark-grey-text">
      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">
          <img src="{{ item.image.url }}" class="img-fluid mt-4" alt="">
        </div>
        <div class="col-md-6 mb-4 information">
          <!--Content-->
          <div class="p-4 content">
            <div class="mt-0">
                <h2>{{ item.title }}<span class="badge badge-{{ item.label_colour }} ml-2">{{ item.labels }}</span></h2>
            </div>
            <div class="lead">
              {% if item.description %}
              <h5>{{ item.description }}</h5>
              {% endif %}
              <h3>Rs.{{ item.price }}</h3>
              <h4>{{ item.instructions }}</h4>
            </div>
            <a href="{% url 'main:add-to-cart' item.slug %}" style="background-color:#47278c;border-style: none;"class="btn btn-success btn-md my-0 p">Add to cart</a>
          </div>
        </div>
      </div>
      <hr>
    </div>
  </main>
  <div class="container">
    <h1 class="text-center">Reviews</h1>
    
    <form action="{% url 'main:cake_reviews' %}" method="POST" class="mb-3">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm-11">
          <input type="text" name="review" class="form-control" placeholder="Enter Your Review">
          <input type="hidden" name="rslug" class="form-control" value="{{item.slug}}">
        </div>
        <div class="col-sm-1">
          <button type="submit" style="background-color: #691d94;border-style: none;"class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>

    {% for review in reviews %}
      <div class="main-reviews card mb-3">
        <div class="card-body">
          <div class="user_details" style="display: flex; border-bottom: 1px solid rgb(31, 30, 30);">
            <h3 class="mr-3">{{ review.user.username }} </h3>
            <p class="mt-2">{{ review.posted_on }}</p>
          </div>
            <h4>{{ review.review }}</h4>
        </div>
      </div>
    {% endfor %}
    
  </div>
</div>
{% endblock content %}